# Generated by Django 3.2.2 on 2022-05-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compounds',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('compound_id', models.PositiveIntegerField(default=1, unique=True, verbose_name='compound ids')),
                ('name', models.CharField(default='', max_length=120, verbose_name='name')),
                ('formula', models.CharField(default='', max_length=120, verbose_name='formula')),
                ('description', models.TextField(default='', verbose_name='descriptions')),
                ('molar_mass', models.FloatField(default=0.0, max_length=5, verbose_name='molar_mass')),
                ('density', models.FloatField(default=0.0, max_length=5, verbose_name='density')),
                ('picture', models.URLField(default='', verbose_name='pictures')),
            ],
        ),
    ]
