# Generated by Django 3.2.2 on 2022-05-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcidificationReference',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_ref', models.CharField(default='', max_length=120, verbose_name='name_ref')),
                ('ap_ref', models.FloatField(default=0.0, max_length=5, verbose_name='ap_ref')),
                ('compound_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='impactos.compounds', verbose_name='Compounds')),
            ],
            options={
                'db_table': 'impactos_acidification',
            },
        ),
    ]
