# Generated by Django 3.2.2 on 2022-05-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impactos', '0003_acidificationreference_formula_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acidificationreference',
            name='compound_id',
        ),
    ]
