# Generated by Django 3.2.2 on 2022-05-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impactos', '0004_remove_acidificationreference_compound_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcidificationCompound',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('num_f', models.FloatField(default=0.0, max_length=5, verbose_name='num_f')),
                ('num_cl', models.FloatField(default=0.0, max_length=5, verbose_name='num_cl')),
                ('num_n', models.FloatField(default=0.0, max_length=5, verbose_name='num_n')),
                ('num_s', models.FloatField(default=0.0, max_length=5, verbose_name='num_s')),
                ('compound_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='impactos.compounds', verbose_name='Compounds')),
            ],
            options={
                'db_table': 'acidification_compounds',
            },
        ),
    ]
